### ISSUE TITLE
[MH] Next.js Portfolio (pjct-next-1-portfolio)

### ISSUE THREAD

**Issue by harenbergm** [harenbergm/portfolio#1]
People are already searching for your portfolio online, so we need to create one to showcase what we are capable of.

Apart from an overview of your current skills and projects, it should also serve as a basis for all future projects.

It should have:

- a showcase of who you are
- a gallery of your projects

## TODOs

- [ ] Choose a portfolio starter from these options:
  - https://github.com/upleveled/next-js-portfolio-web
  - https://github.com/upleveled/portfolio-cms
  - https://github.com/upleveled/next-starter-peacock (this portfolio requires additional setup)
  - https://github.com/upleveled/next-portfolio-dev (this portfolio requires additional setup)

> **Note:** you can see the deployed website of the template using the link to the right of the green **Code** button

- [ ] Create a `projects` folder in your home directory (`mkdir projects`) - if it tells you that it already exists, just check this step off and continue with the next step
- [ ] Switch into that new directory (`cd projects`)
- [ ] Clone the repo of the chosen portfolio (`git clone <repo URL>`)
- [ ] `cd` into the directory (`cd <portfolio directory>`)
- [ ] Install dependencies (`yarn`)
- [ ] Open the project in VS Code (`code .`)
- [ ] Make a small change to the README.md file (add an extra space or something)
- [ ] Add all files and make your first commit - check out the [Git commit message guide](https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/cheatsheet-git-github/#writing-commit-messages)
- [ ] Start the server (`yarn dev`)
- [ ] Open the project in VS Code, explore the project structure, find the placeholders for personal information, and update the individual info for yourself
- [ ] Commit the changes
- [ ] Create a new repository on GitHub called `portfolio`
- [ ] Copy the URL and add update the remote URL (`git remote set-url origin https://...`)
- [ ] Push it to GitHub
- [ ] Deploy it using [Netlify](https://www.netlify.com/)
- [ ] Go to the [UpLeveled ESLint configuration GitHub repo](https://github.com/upleveled/eslint-config-upleveled) and copy and run the setup commands in your terminal
- [ ] Add the deployed website URL to your GitHub repo as the URL (see [Documentation](https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/documentation/))
- [ ] Add a comment to this issue with your GitHub repo URL 👇
- [ ] Add a comment to this issue with your deployed website URL 👇

Common commands: https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/cheatsheet-command-line/#common-commands

## Stretch TODOs

- [ ] Add a readme to your project (see [Documentation](https://learn.upleveled.io/courses/btcmp-l-webfs-gen-0/modules/documentation/))
- [ ] Make further changes that you want to the design or content of the website

## Acceptance Criteria

- [ ] [Preflight](https://www.npmjs.com/package/@upleveled/preflight) runs through with only an "ESLint" error in your project (just run `preflight`)
- [ ] Link to GitHub repo in comment below
